{% set name = "cargo-bundle-licenses" %}
{% set version = "4.2.0" %}
{% set sha256 = "196d27676dae302d3c91315c1323b790f13b838b6dfd67b2f6c0236a55547765" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
  url: https://github.com/sstadick/cargo-bundle-licenses/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

outputs:
  - name: {{ name }}
    script: build-unix.sh  # [not win]
    script: bld-win.bat  # [win]
    requirements:
      build:
        - {{ compiler('rust') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - cargo-auditable
        - pkg-config
    test:
      commands:
        - cargo-bundle-licenses --help

  - name: {{ name }}-gnu
    build:
      skip: true  # [not win64]
    script: bld-win.bat
    requirements:
      build:
        - rust-gnu_win-64
        - {{ compiler('rust-gnu') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - {{ compiler('m2w64_c') }}
        - cargo-auditable
        - pkg-config
        - msys2-make
        - cmake
        - libgit2
    test:
      commands:
        - cargo-bundle-licenses --help

about:
  home: https://github.com/sstadick/cargo-bundle-licenses
  license: MIT and Apache-2.0
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Bundle thirdparty licenses for Cargo projects into a single file.
  description: A rust tool to bundle all third-party licenses into a single file.
  dev_url: https://github.com/sstadick/cargo-bundle-licenses
  doc_url: https://github.com/sstadick/cargo-bundle-licenses

extra:
  recipe-maintainers:
    - sstadick
