{% set version = "0.4.0" %}
{% set version = "1.0.1" %}
{% set sha256 = "89a3725340ac0a5aca6fc198cacab440ba46ef6e3c052ea9aca5cf751aafbfea" %}

package:
  name: cargo-bundle-licenses
  version: {{ version }}

source:
  url: https://github.com/sstadick/cargo-bundle-licenses/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}  # must be rustc=>1.56.1
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - pkg-config
    #- make # [not win]
    #- ninja # [win
    #- cmake
    - zlib
  host:
    - zlib
  run:
    - libiconv

test:
  commands:
    - cargo-bundle-licenses --help

about:
  home: https://github.com/sstadick/cargo-bundle-licenses
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  license_url: https://raw.githubusercontent.com/sstadick/cargo-bundle-licenses/main/LICENSE-MIT
  dev_url: https://github.com/sstadick/cargo-bundle-licenses
  description: "Bundle all third-party licenses into a single file."
  doc_source_url: https://github.com/sstadick/cargo-bundle-licenses
  doc_url: https://github.com/sstadick/cargo-bundle-licenses
  summary: Bundle thirdparty licenses for Cargo projects into a single file.

extra:
  recipe-maintainers:
    - sstadick

